InterestCalculator/Models/CalculatorModel.cs
namespace InterestCalculator.Models
{
    public class CalculatorModel
    {
        public decimal PurchaseAmount { get; set; }
        public int Installments { get; set; }

        public decimal Interest { get; set; }
        public InterestType InterestType { get; set; }
        public List<Payment> PaymentPlan { get; set; } = new List<Payment>();


        public void CalculatePaymentPlan()
        {
            decimal monthlyRate;
            if( InterestType == InterestType.effectiveAnnualRate)
            {
                monthlyRate = (decimal)Math.Pow((double)(1 + (Interest/100)), 1.0 / 12) - 1;
            }
            else
            {
                monthlyRate = Interest / 100;
            }

            decimal monthlyPrincipalPayment = PurchaseAmount / Installments;

            decimal remainingAmount = PurchaseAmount;

            for (int i = 1; i <= Installments; i++)
            {
                decimal interestPaid = remainingAmount * monthlyRate;
                decimal paymentAmount = monthlyPrincipalPayment + interestPaid;
                remainingAmount = remainingAmount - monthlyPrincipalPayment;

                PaymentPlan.Add(new Payment
                {
                    InstallmentNumber = i,
                    PrincipalPaid = monthlyPrincipalPayment,
                    InterestPaid = interestPaid,
                    PaymentAmount = paymentAmount,
                    RemainingPrincipal = remainingAmount

                });
            }

        }



    }
}

InterestCalculator/Models/ErrorViewModel.cs
namespace InterestCalculator.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InterestCalculator/Models/InterestType.cs
namespace InterestCalculator.Models
{
    public enum InterestType
    {
        effectiveAnnualRate,
        Monthly
    }
}

InterestCalculator/Models/Payment.cs
namespace InterestCalculator.Models
{
    public class Payment
    {
        public int InstallmentNumber { get; set; }
        public decimal PrincipalPaid { get; set; }
        public decimal InterestPaid { get; set; }
        public decimal RemainingPrincipal { get; set; }
        public decimal PaymentAmount { get; set; }
        public DateTime DueDate { get; set; }
    }
}

InterestCalculator/Controllers/CalculatorController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using InterestCalculator.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Globalization;
using System.Reflection;

namespace InterestCalculator.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            var model = new CalculatorModel();
            return View(model);
        }

        public IActionResult Calculate(CalculatorModel model) {

            // Fix decimal issue
            decimal interest;
            bool isSuccess = decimal.TryParse(model.Interest.ToString(), out interest);
            if (isSuccess)
            {
                model.Interest = interest;

                if (ModelState.IsValid)
                {
                    model.CalculatePaymentPlan();
                    return View("PaymentPlan", model);
                }
            }           

            return View("Index", model);
        }

        public IActionResult Export(CalculatorModel model)
        {
            decimal interest;
            bool isSuccess = decimal.TryParse(model.Interest.ToString(), out interest);
            if (isSuccess)
            {
                model.Interest = interest;
                model.CalculatePaymentPlan();
            }
            
            var wb = new XLWorkbook();
                var ws = wb.Worksheets.Add("Payment plan");

            // Setup columns
            ws.Cell(1, 1).Value = "Installment";
            ws.Cell(1, 2).Value = "Principal paid";
            ws.Cell(1, 3).Value = "Interest paid";
            ws.Cell(1, 4).Value = "Payment amount";
            ws.Cell(1, 5).Value = "Remaining amount";

            setHeadersFormat(wb, ws);

            int currentRow = 2;
            // Filing rows
            foreach (Payment row in model.PaymentPlan)
            { 
                ws.Cell(currentRow, 1).Value = row.InstallmentNumber;
                ws.Cell(currentRow, 2).Value = row.PrincipalPaid;
                ws.Cell(currentRow, 3).Value = row.InterestPaid;
                ws.Cell(currentRow, 4).Value = row.PaymentAmount;
                ws.Cell(currentRow, 5).Value = row.RemainingPrincipal;
                currentRow++;
            }

            int finalRow = currentRow - 1;
            setDataFormat(wb, ws, finalRow.ToString());
            setTableBorderFormat(wb, ws, finalRow.ToString());

            var stream = new MemoryStream();
            wb.SaveAs(stream);
            stream.Position = 0;

            return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "payment_plan.xlsx");
        }

        private void setHeadersFormat(IXLWorkbook wb, IXLWorksheet ws)
        {
            var range = ws.Range("A1:E1");

            range.Style.Font.Bold = true;

            range.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            range.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;

            ws.Columns().AdjustToContents();
        }

        private void setDataFormat(IXLWorkbook wb, IXLWorksheet ws, string finalRow)
        {
            var dataRange = ws.Range("A2:E" + finalRow);

            dataRange.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            dataRange.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;

            var currencyRange = ws.Range("B2:E" + finalRow);
            currencyRange.Style.NumberFormat.Format = "$#,##0;-$#,##0";

            ws.Columns().AdjustToContents();
        }

        private void setTableBorderFormat(IXLWorkbook wb, IXLWorksheet ws, string finalRow)
        {
            var range = ws.Range("A1:E"+finalRow);

            range.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
            range.Style.Border.OutsideBorderColor = XLColor.Black;
            range.Style.Border.InsideBorder = XLBorderStyleValues.Thin;
            range.Style.Border.InsideBorderColor = XLColor.Black;

            ws.Columns().AdjustToContents();
        }
    }
}

InterestCalculator/Views/Calculator/Index.cshtml
@model CalculatorModel

<h1 class="text-center">Interest calculator</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="Calculate" method="post">
                <div class="mb-3">
                    <label class="form-label" asp-for="PurchaseAmount">Purchase Amount:</label>
                    <input class="form-control" asp-for="@Model.PurchaseAmount" />
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="Installments">Installments:</label>
                    <input class="form-control" asp-for="@Model.Installments" />
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="Interest">Interest rate (%):</label>
                    <input class="form-control" asp-for="@Model.Interest">
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="InterestType">Interest Type:</label>
                    <select class="form-select" asp-for="InterestType">
                        <option value="0">Effective Annual Rate</option>
                        <option value="1">Monthly</option>
                    </select>
                </div>

                <button class="btn btn-primary" type="submit">Calculate</button>
            </form>
        </div>
    </div>
</div>

InterestCalculator/Views/Calculator/PaymentPlan.cshtml
@model CalculatorModel

<h2 class="text-center">Payment plan</h2>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="Export" method="post">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Installment</th>
                            <th>Principal paid</th>
                            <th>Interest paid</th>
                            <th>Payment amount</th>
                            <th>Remaining amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var payment in Model.PaymentPlan)
                        {
                            <tr>
                                <td>@payment.InstallmentNumber</td>
                                <td>@payment.PrincipalPaid.ToString("C")</td>
                                <td>@payment.InterestPaid.ToString("C")</td>
                                <td>@payment.PaymentAmount.ToString("C")</td>
                                <td>@payment.RemainingPrincipal.ToString("C")</td>
                            </tr>
                        }
                    </tbody>
                </table>

                @* Information for the export *@
                <input type="hidden" asp-for="@Model.PurchaseAmount" />
                <input type="hidden" asp-for="@Model.Installments" />
                <input type="hidden" asp-for="@Model.Interest" />
                <input type="hidden" asp-for="@Model.InterestType" />
                <input type="hidden" asp-for="@Model.PaymentPlan" />

                <div class="text-center">
                    <a class="btn btn-outline-primary" asp-action="Index">Back</a>
                    <button type="submit" class="btn btn-outline-success">Export to Excel</button>
                </div>
            </form>
        </div>
    </div>
</div>

InterestCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InterestCalculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InterestCalculator.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Calculator" asp-action="Index">InterestCalculator</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - InterestCalculator
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>